export const PRIMARY_BACKGROUND_COLOR = '#FFFFFF';
export const SECONDARY_BACKGROUND_COLOR = '#F8F8F8';
export const TERTIARY_BACKGROUND_COLOR = '#FD114A';
export const QUATERNARY_BACKGROUND_COLOR = '#2C2C31';
export const QUINARY_BACKGROUND_COLOR = '#1ABBBC';
export const SENARY_BACKGROUND_COLOR = '#F7FBFB';
export const SEPTENARY_BACKGROUND_COLOR = '#22FF00';
export const OCTONARY_BACKGROUND_COLOR = '#313234';
export const NONARY_BACKGROUND_COLOR = '#CCCCCC';
export const DENARY_BACKGROUND_COLOR = '#FFC44D';
export const UNDENARY_BACKGROUND_COLOR = '#000000';
export const DUODENARY_BACKGROUND_COLOR = '#3E4958';
export const THRIODENARY_BACKGROUND_COLOR = '#FEF5F5';
export const QUADENARY_BACKGROUND_COLOR = '#0D0D0F';
export const QUIDENARY_BACKGROUND_COLOR = '#313234';
export const SENDENARY_BACKGROUND_COLOR = '#1E1E1E';
export const OCTODENARY_BACKGROUND_COLOR = '#F7F8F9';

export const PRIMARY_TEXT_COLOR = '#626262';
export const SECONDARY_TEXT_COLOR = '#B3B8C7';
export const TERTIARY_TEXT_COLOR = '#666977';
export const QUATERNARY_TEXT_COLOR = '#FFFFFF';
export const QUINARY_TEXT_COLOR = '#CCD2E3';
export const SENARY_TEXT_COLOR = '#C1C1C1';
export const SEPTENARY_TEXT_COLOR = '#246EE9';
export const OCTONARY_TEXT_COLOR = '#494B4B';
export const NONARY_TEXT_COLOR = '#3A3A3C';
export const DENARY_TEXT_COLOR = '#000000';
export const UNDENARY_TEXT_COLOR = '#4B545A';
export const DUODENARY_TEXT_COLOR = '#443F3F';
export const THRIODENARY_TEXT_COLOR = '#7E7E7E';
export const QUADENARY_TEXT_COLOR = '#A7A8AF';
export const QUIDENARY_TEXT_COLOR = '#443F3F';
export const SENDENARY_TEXT_COLOR = '#22FF00';
export const SEPTDENARY_TEXT_COLOR = '#3E82C6';
export const OCTODENARY_TEXT_COLOR = '#FFC44D';
export const NONDENARY_TEXT_COLOR= '#3E4958';

export const PRIMARY_HEADING_COLOR = '#626262';
export const SECONDARY_HEADING_COLOR = '#666977';

export const PRIMARY_BUTTON_COLOR = '#0e3560';
export const SECONDARY_BUTTON_COLOR = '#FFFFFF';
export const TERTIARY_BUTTON_COLOR = '#FD114A';
export const PRIMARY_BUTTON_TEXT_COLOR = '#FFFFFF';
export const SECONDARY_BUTTON_TEXT_COLOR = '#246EE9';

export const PRIMARY_LABEL_COLOR = '#FFFFFF';
export const SECONDARY_LABEL_COLOR = '#CCD2E3';

export const PRIMARY_BORDER_COLOR = '#D7D7D7';
export const SECONDARY_BORDER_COLOR = '#BEBEBE';
export const TERTIARY_BORDER_COLOR = '#246EE9';
export const QUATERNARY_BORDER_COLOR = '#A7A7A9';
export const QUINARY_BORDER_COLOR = '#FD114A';
export const SENARY_BORDER_COLOR = '#313234';
export const SEPTENARY_BORDER_COLOR = '#E2E2E2';
export const OCTONARY_BORDER_COLOR = '#CCCCCC';
export const NONARY_BORDER_COLOR = '#B1B1B1';
export const DENARY_BORDER_COLOR = '#747E8F';
export const UNDENARY_BORDER_COLOR = '#FFFFFF';
export const DUODENARY_BORDER_COLOR = '#D5DDE0';
export const THRIODENARY_BORDER_COLOR = '#000000';
export const QUADENARY_BORDER_COLOR = '#22FF00';
export const QUIDENARY_BORDER_COLOR = '#717171';

export const PRIMARY_INPUT_TEXT_COLOR = '#B3B8C7';
export const SECONDARY_INPUT_TEXT_COLOR = '#666977';
export const TERTIARY_INPUT_TEXT_COLOR = '#7E7E7E';
export const PRIMARY_INPUT_TEXT_BACKGROUND_COLOR = '#121212';
export const SECONDARY_INPUT_TEXT_BACKGROUND_COLOR = '#FFFFFF';

export const PRIMARY_ERROR_COLOR = 'red';

export const PRIMARY_SUCCESS_COLOR = 'green';


