export const FONT_NORMAL = 'OpenSans-Regular';
export const FONT_MEDIUM = 'Mulish-Medium';
export const FONT_BOLD = 'OpenSans-Bold';
export const FONT_SEMI_BOLD = 'OpenSans-Medium';
export const FONT_EXTRA_BOLD = 'OpenSans-ExtraBold';
export const FONT_SF_REGULAR='SF-Pro-Text-Regular';
export const FONT_SF_BOLD='OpenSans-Bold'; // Changed from SF-Pro-Text-Bold because of the ios project  error
export const FONT_SF_SEMIBOLD='OpenSans-Bold';
export const FONT_SF_MEDIUM='OpenSans-Medium'; // Changed from SF-Pro-Text-Medium because of the ios project  error
export const FONT_SF_BLACK='OpenSans-Bold';
export const FONT_SF_HEAVY='OpenSans-Bold';
export const FONT_SF_LIGHT='OpenSans-Bold';
export const FONT_SIZE_TINY = 9;
export const FONT_SIZE_TINY_PLUS = 10;
export const FONT_SIZE_SMALL = 12;
export const FONT_SIZE_MEDIUM = 14;
export const FONT_SIZE_LARGE = 16;
export const FONT_SIZE_EXTRA_LARGE = 18;
export const FONT_SIZE_EXTRA_LARGE_PLUS = 20;
export const FONT_SIZE_DOUBLE_EXTRA_LARGE_MINUS = 22;
export const FONT_SIZE_DOUBLE_EXTRA_LARGE = 24;
export const FONT_SIZE_DOUBLE_EXTRA_LARGE_PLUS = 26;
export const FONT_WEIGHT_LIGHT = 200;
export const FONT_WEIGHT_MEDIUM = 600;
export const FONT_WEIGHT_HEAVY = 800;
